### PR TITLE
add support for retrieving function trims

### PR DESCRIPTION
**Pull request by michi42**
small change set to support the retrieval of functions from LSA trims (e.g. squeeze etc.)

### CODE REVIEW

**Comment by rdemaria** [comment]
It is not a strong point, but would it make sense to export only the timestamp and data in the dictionary to be pytimber compatible and write an additional method on the trim headers? In particular as you said that headers are very fast.

**Comment by michi42** [comment]
Fine for me, although I think the additional element in the tuple won't break anything in most cases, as people still get timestams in [0] and data in [1].

What I by the way also wanted to suggest - could we return a namedtuple (with same field names) in pytimber as well? A namedtuple is still a tuple (and thus accessible by index, iterable etc.), but additionally exposes some properties which refer more explicitly to the contents. So e.g.
```doSometing(result.time, result.data)```
would be fully equivalent to
```doSometing(result[0], result[1])```
but it helps you to get what means what e.g. in tab autocompletion...

**Comment by rdemaria** [comment]
I think it is a very good idea also for pytimber. Do you know if it is pickable? I am hesitating between calling it timestamps, time, ts, or t for the first element. data is good.

**Comment by rdemaria** [comment]
In some code I use t,v=db.get(....)['var']. With a third element this code will break. I think we would need to wait to the next year for pytimber...

**Comment by michi42** [comment]
Indeed, list unpacking is one of the cases which break. So fine for me to remove it. Or we can put it in the parent dictionary as 'trimHeaders', as it will be the same for all parameters anyway, then you can still do t,v=dict['param']

But the namedtuple should not break this, unpacking works exactly as the regular tuple.

**Comment by michi42** [comment]
I just added a small commit to remove the headers from the tuple and put them into the toplevel dict instead (as 'trimHeaders')

**Comment by rdemaria** [comment]
One feature of pagestore is that you can do pgdb.store(db.get(...)). In that case trimheaders will be always imported. I think the idea of a named tuple is a good one and more stable for future extensions. We don't need to decide now, though, let's see what is more convenient for you.

**Comment by michi42** [comment]
I see. Then let's remove them for the time being, as you said, there is an extra method to get the trim headers and it's not much overhead ...

**Pull request merged**
